# Generated by Django 3.2.5 on 2021-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='image',
            field=models.ImageField(upload_to='static/blog'),
        ),
    ]
